const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('../../app/node_modules/typescript');
const out={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/src/services/basemap-catalog.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:out});
const row={name:'test.pmtiles',label:'Test',url:'static/offline-maps/test.pmtiles',bytes:127,sha256:'a'.repeat(64),attribution:'OSM',license:'ODbL-1.0 Produced Work'};
test('catalog rejects duplicate names, external URLs and missing rights',()=>{for(const rows of [[],[row,row],[{...row,url:'https://other/map'}],[{...row,attribution:''}],[{...row,bytes:NaN}]])assert.throws(()=>out.validateMapCatalog(rows));});
test('success refresh coalesces and keeps independent snapshots',async()=>{let calls=0;const store=out.createMapCatalog([row],async()=>{calls++;return JSON.stringify([{...row,label:'New'}]);});const [a,b]=await Promise.all([store.refresh(),store.refresh()]);assert.equal(calls,1);assert.equal(a[0].label,'New');a[0].label='Changed';assert.equal(b[0].label,'New');await store.refresh();assert.equal(calls,1);});
test('failed refresh preserves seed and uses retry cooldown',async()=>{let now=100,calls=0;const store=out.createMapCatalog([row],async()=>{calls++;throw Error('offline');},()=>now);await assert.rejects(store.refresh());assert.equal(store.snapshot()[0].label,'Test');await store.refresh();assert.equal(calls,1);now+=60001;await assert.rejects(store.refresh());assert.equal(calls,2);});
test('synchronous adapter failure does not leave a stuck pending promise',async()=>{let now=100,calls=0;const store=out.createMapCatalog([row],()=>{calls++;throw Error('sync');},()=>now);await assert.rejects(store.refresh());now+=60001;await assert.rejects(store.refresh());assert.equal(calls,2);});
test('malformed or oversized remote response never replaces catalog',async()=>{for(const text of ['{}','x'.repeat(256*1024+1)]){const store=out.createMapCatalog([row],async()=>text);await assert.rejects(store.refresh());assert.equal(store.snapshot()[0].name,'test.pmtiles');}});

test('desktop uses fixed public distribution and browser keeps local base',()=>{assert.equal(out.mapDistributionBase(true,'tauri://localhost/'),out.PUBLIC_MAP_DISTRIBUTION);assert.equal(out.mapDistributionBase(false,'https://example.test/client-app/'),'https://example.test/client-app/');});
