const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const ts=require('../../app/node_modules/typescript');
const exportsObject={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(require.resolve('../../app/src/services/catalog-file-chunks.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:exportsObject});
const {readChunkedCatalog,writeChunkedCatalog}=exportsObject;
function fixture(){const files=new Map(),writes=[];return {files,writes,api:{read:async name=>{if(!files.has(name))throw new Error('missing');const text=files.get(name);if(Buffer.byteLength(text)>10*1024*1024)throw new Error('simulated large transfer restriction');return text;},write:async(name,text)=>{files.set(name,text);writes.push(name);}}};}
test('large public catalog restores through bounded transfers',async()=>{const f=fixture(),text=JSON.stringify({routes:Array.from({length:40000},(_,i)=>({id:i,name:'路线'.repeat(60)}))});assert.ok(Buffer.byteLength(text)>10*1024*1024);await writeChunkedCatalog(f.api,'catalog',text);assert.equal(await readChunkedCatalog(f.api,'catalog'),text);assert.equal(f.writes.at(-1),'catalog.parts.json');for(const [name,value] of f.files)assert.ok(Buffer.byteLength(value)<2*1024*1024,name);});
test('surrogate boundary preserves unicode exactly',async()=>{const f=fixture(),text='a'.repeat(512*1024-1)+'🌍'+'b';await writeChunkedCatalog(f.api,'catalog',text);assert.equal(await readChunkedCatalog(f.api,'catalog'),text);});
test('legacy small file remains readable without manifest',async()=>{const f=fixture();f.files.set('catalog','legacy');assert.equal(await readChunkedCatalog(f.api,'catalog'),'legacy');});
test('missing/truncated part is rejected rather than returned',async()=>{const f=fixture();await writeChunkedCatalog(f.api,'catalog','a'.repeat(700000));f.files.set('catalog.part-1','short');await assert.rejects(readChunkedCatalog(f.api,'catalog'));f.files.delete('catalog.part-1');await assert.rejects(readChunkedCatalog(f.api,'catalog'));});
test('invalid manifest does not silently restore legacy data',async()=>{const f=fixture();f.files.set('catalog','old');f.files.set('catalog.parts.json',JSON.stringify({format:'wrong',parts:1}));await assert.rejects(readChunkedCatalog(f.api,'catalog'));});
test('oversize catalog is rejected before writing',async()=>{const f=fixture();await assert.rejects(writeChunkedCatalog(f.api,'catalog','a'.repeat(24*1024*1024+1)));assert.equal(f.writes.length,0);});
test('failed part write never commits its manifest',async()=>{const f=fixture();f.api.write=async(name,text)=>{if(name.endsWith('part-1'))throw new Error('disk full');f.files.set(name,text);};await assert.rejects(writeChunkedCatalog(f.api,'catalog','a'.repeat(700000)));assert.equal(f.files.has('catalog.parts.json'),false);});
