const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../../shared/network/relay-v1/relay.js'),'utf8');
function fixture(){let handler;const calls=[],replies=[],parent={postMessage:(value,origin)=>replies.push({value,origin})};
 const context={parent,window:{addEventListener:(_,fn)=>handler=fn},TextEncoder,AbortSignal,fetch:async(url,options)=>{calls.push({url,options});return {status:200,text:async()=>JSON.stringify({ok:true,data:{status:'available'}})};}};
 vm.runInNewContext(source,context);
 const input={type:'hiking-relay-request-v1',id:'a'.repeat(32),action:'weather.forecast',data:{latitude:34.49,longitude:113.06}};
 return {calls,replies,parent,input,send:handler};}
test('foreign origins and unrelated windows cannot issue requests',async()=>{const f=fixture();await f.send({source:f.parent,origin:'https://evil.example',data:f.input});await f.send({source:{},origin:'https://hiking-earth.nanyu20050927.chatgpt.site',data:f.input});assert.equal(f.calls.length,0);assert.equal(f.replies.length,0);});
test('fixed endpoint and cookie-free request preserve real action and response',async()=>{const f=fixture();await f.send({source:f.parent,origin:'https://hiking-earth.nanyu20050927.chatgpt.site',data:f.input});assert.equal(f.calls.length,1);assert.match(f.calls[0].url,/\.app\.tcloudbase\.com\/client-api$/);assert.equal(f.calls[0].options.credentials,'omit');assert.equal(JSON.parse(f.calls[0].options.body).action,'weather.forecast');assert.equal(f.replies[0].origin,'https://hiking-earth.nanyu20050927.chatgpt.site');assert.equal(f.replies[0].value.status,200);});
test('invalid token and action are rejected before network',async()=>{const f=fixture();for(const change of [{token:'bad'},{action:'https://evil.example'},{id:'bad'}])await f.send({source:f.parent,origin:'https://hiking-earth.nanyu20050927.chatgpt.site',data:{...f.input,...change}});assert.equal(f.calls.length,0);});
test('bearer is only forwarded to fixed backend, never reflected',async()=>{const f=fixture();await f.send({source:f.parent,origin:'https://hiking-earth.nanyu20050927.chatgpt.site',data:{...f.input,token:'b'.repeat(64)}});assert.equal(f.calls[0].options.headers.Authorization,'Bearer '+'b'.repeat(64));assert.ok(!JSON.stringify(f.replies).includes('b'.repeat(64)));});
