const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const ts=require('../../app/node_modules/typescript'),pmtiles=require('../../app/node_modules/pmtiles');
const exportsObject={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(require.resolve('../../app/src/services/local-basemap.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:exportsObject,ArrayBuffer,require:()=>pmtiles});
const {openLocalBasemap,localBasemapStyle}=exportsObject;
const sample='/Users/nanyu/.local/share/hiking-earth/acceptance/offline-maps/lantau.pmtiles';
function fixture(){const buffer=fs.readFileSync(sample),calls=[];return {buffer,calls,read:async(offset,length)=>{calls.push({offset,length});const b=buffer.subarray(offset,offset+length);return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);}};}
test('reject invalid identities and sizes before any reads',async()=>{for(const [id,size] of [['../bad',128],['good',0],['good',64*1024*1024+1]])await assert.rejects(openLocalBasemap(id,size,async()=>{throw new Error('must not read');}));});
test('local geometry style has no external fonts/sprites/style URL',()=>{const s=localBasemapStyle('offline-basemap-test');assert.equal(s.sources.basemap.url,'pmtiles://offline-basemap-test');assert.equal(s.glyphs,undefined);assert.equal(s.sprite,undefined);assert.ok(s.layers.some(l=>l.id==='paths'));assert.throws(()=>localBasemapStyle('https://remote'));});
test('actual region reads its header, metadata and center tile locally',{skip:!fs.existsSync(sample)},async()=>{const f=fixture();const result=await openLocalBasemap('lantau',f.buffer.length,f.read);assert.equal(result.header.maxZoom,15);const metadata=await result.archive.getMetadata();assert.ok(metadata.vector_layers.some(l=>l.id==='roads'));const z=15,x=Math.floor((113.955+180)/360*2**z),lat=22.23*Math.PI/180,y=Math.floor((1-Math.asinh(Math.tan(lat))/Math.PI)/2*2**z);const tile=await result.archive.getZxy(z,x,y);assert.ok(tile?.data.byteLength>0);assert.ok(f.calls.every(c=>c.length<=8*1024*1024));});
test('range reader rejects unsafe offsets, large reads, truncation and cancellation',{skip:!fs.existsSync(sample)},async()=>{const f=fixture();const {archive}=await openLocalBasemap('safe',f.buffer.length,f.read);await assert.rejects(archive.source.getBytes(-1,1));await assert.rejects(archive.source.getBytes(0,9*1024*1024));await assert.rejects(archive.source.getBytes(f.buffer.length,1));await assert.rejects(archive.source.getBytes(0,1,{aborted:true}));await assert.rejects(openLocalBasemap('short',f.buffer.length,async()=>new ArrayBuffer(1)));});
