const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('../../app/node_modules/typescript');
function load(path,deps={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports,require:n=>deps[n],setTimeout,clearTimeout,ArrayBuffer,Uint8Array});return exports;}
const ranges=load('app/src/services/basemap-file-reader.ts'),native=load('app/src/services/native-basemap-reader.ts',{'./basemap-file-reader':ranges});
function fixture({size=256,content,throws=false}={}){let sliced,closed=0;class Reader{readAsDataURL(){if(throws)throw Error();this.result=content??'data:application/octet-stream;base64,'+Buffer.alloc(sliced[1]-sliced[0],7).toString('base64');this.onload();}abort(){this.onabort?.();}}
const io={FileReader:Reader,resolveLocalFileSystemURL:(path,ok)=>ok({file:ok=>ok({size,slice:(a,b)=>{sliced=[a,b];return {close:()=>closed++}},close:()=>closed++})})};return {io,slice:()=>sliced,closed:()=>closed};}
const decode=s=>Uint8Array.from(Buffer.from(s,'base64')).buffer;
test('native range reads only requested bytes and closes file handles',async()=>{const f=fixture();const data=await native.nativeMapRangeReader(f.io,'_doc/map.pmtiles',256,decode)(20,32);assert.equal(data.byteLength,32);assert.deepEqual(f.slice(),[20,52]);assert.equal(f.closed(),2);});
test('native range rejects changed size, malformed data and synchronous read failures',async()=>{for(const options of [{size:255},{content:'data:application/octet-stream;base64,!!!!'},{throws:true}]){const f=fixture(options);await assert.rejects(native.nativeMapRangeReader(f.io,'_doc/map.pmtiles',256,decode)(20,32));assert.ok(f.closed()>=1);}});
test('invalid range never opens native file',async()=>{const f=fixture();await assert.rejects(native.nativeMapRangeReader(f.io,'_doc/map.pmtiles',256,decode)(-1,32));assert.equal(f.slice(),undefined);});
