const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('../../app/node_modules/typescript');
function setup(){
 const exported={},elements=[],markers=[];
 const shapeExports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/src/services/basemap-canvas.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:shapeExports,require:()=>({})});
 const source=fs.readFileSync('app/src/components/OfflineBasemap.vue','utf8').split('<script setup lang="ts">')[1].split('</script>')[0]+ '\nexport {drawLabels};export function bindMap(value:LibreMap){map=value;}';
 class Marker{constructor(options){this.element=options.element;this.removed=false;markers.push(this);}setLngLat(c){this.coordinates=c;return this;}addTo(){return this;}remove(){this.removed=true;}}
 vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:exported,defineProps:()=>({file:null}),document:{createElement:()=>{const element={style:{}};elements.push(element);return element;}},require:name=>name==='vue'?{ref:v=>({value:v}),watch:()=>{},onUnmounted:()=>{},nextTick:async()=>{}}:name==='maplibre-gl'?{Marker,setWorkerUrl:()=>{}}:name==='@/services/basemap-canvas'?shapeExports:{} });
 let shift=0;const current={isStyleLoaded:()=>true,querySourceFeatures:(_,options)=>options.sourceLayer==='places'?[{geometry:{type:'Point',coordinates:[10,10]},properties:{'name:zh':'山顶',name:'Peak'}}]:[{geometry:{type:'Point',coordinates:[20,20]},properties:{name:'<img onerror=x>'}}],project:([x,y])=>({x:x*10+shift,y:y*10}),getCanvas:()=>({clientWidth:500,clientHeight:420})};
 exported.bindMap(current);return {exported,current,elements,markers,move:()=>{shift=20;}};
}
test('web map labels use plain text and stable idle does not recreate markers',()=>{const s=setup();s.exported.drawLabels(s.current);assert.equal(s.markers.length,2);assert.equal(s.elements[0].textContent,'山顶');assert.equal(s.elements[1].textContent,'<img onerror=x>');assert.ok(s.elements.every(e=>e.innerHTML===undefined));s.exported.drawLabels(s.current);assert.equal(s.markers.length,2);assert.ok(s.markers.every(m=>!m.removed));});
test('web label movement updates bounded markers and releases old ones',()=>{const s=setup();s.exported.drawLabels(s.current);s.move();s.exported.drawLabels(s.current);assert.equal(s.markers.length,4);assert.ok(s.markers.slice(0,2).every(m=>m.removed));assert.ok(s.markers.slice(2).every(m=>!m.removed));});
test('malformed label source cleans labels without throwing away the map',()=>{const s=setup();s.exported.drawLabels(s.current);s.current.querySourceFeatures=()=>{throw new Error('damaged tile')};assert.doesNotThrow(()=>s.exported.drawLabels(s.current));assert.ok(s.markers.every(m=>m.removed));});
