const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const ts=require('../../site-release/node_modules/typescript');
const code=ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../../site-release/app/api/client-api/route.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const exportsObject={};new Function('require','exports',code)(()=>({NextResponse:{json:Response.json}}),exportsObject);
test('same-origin proxy fixes destination and forwards bearer without caching',async()=>{const original=global.fetch;let call;
 global.fetch=async(url,options)=>{call={url,options};return Response.json({ok:false,code:'SESSION_EXPIRED',errMsg:'expired'},{status:401});};
 try{const response=await exportsObject.POST(new Request('https://example.org/api/client-api',{method:'POST',headers:{Authorization:'Bearer '+'a'.repeat(64)},body:JSON.stringify({action:'auth.profile',data:{}})}));assert.equal(response.status,401);assert.equal(response.headers.get('cache-control'),'no-store');assert.equal((await response.json()).code,'SESSION_EXPIRED');assert.match(call.url,/\.app\.tcloudbase\.com\/client-api$/);assert.equal(call.options.redirect,'manual');assert.equal(call.options.headers.Authorization,'Bearer '+'a'.repeat(64));}finally{global.fetch=original;}
});
test('redirect does not forward credentials to another host',async()=>{const original=global.fetch;let count=0;global.fetch=async()=>{count++;return new Response('',{status:302,headers:{Location:'https://evil.example'}});};try{const response=await exportsObject.POST(new Request('https://example.org/api/client-api',{method:'POST',body:JSON.stringify({action:'weather.forecast',data:{}})}));assert.equal(response.status,502);assert.equal(count,1);}finally{global.fetch=original;}});
test('invalid bearer, malformed JSON and oversized body never reach cloud',async()=>{const original=global.fetch;global.fetch=async()=>{throw new Error('must not call');};try{for(const [headers,body,status] of [[{Authorization:'Bearer invalid'},'{}',400],[{},'not json',400],[{},'a'.repeat(6*1024*1024+1),413]])assert.equal((await exportsObject.POST(new Request('https://example.org/api/client-api',{method:'POST',headers,body}))).status,status);}finally{global.fetch=original;}});
