const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('../../app/node_modules/typescript'),crypto=require('node:crypto');
function moduleAt(path,deps,extra={}){const out={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:out,ArrayBuffer,Uint8Array,require:n=>deps[n],...extra});return out;}
const digest=moduleAt('app/src/services/basemap-digest.ts',{'@noble/hashes/sha256':require('../../app/node_modules/@noble/hashes/sha256')}),reader=moduleAt('app/src/services/basemap-file-reader.ts',{});let timeout;
const download=moduleAt('app/src/services/wechat-basemap-download.ts',{'./basemap-digest':digest,'./basemap-file-reader':reader},{setTimeout:cb=>{timeout=cb;return 1;},clearTimeout:()=>{}}).downloadWechatBasemap;
function fixture(){const b=Buffer.alloc(127),state={aborts:0,url:'',progress:null,status:200,size:127,holdInfo:false},pack={name:'test.pmtiles',url:'static/offline-maps/test.pmtiles',bytes:127,sha256:crypto.createHash('sha256').update(b).digest('hex')};const api={downloadFile:o=>{state.url=o.url;queueMicrotask(()=>{state.progress?.({totalBytesWritten:127,totalBytesExpectedToWrite:127});o.success({statusCode:state.status,tempFilePath:'http://tmp/test'});});return {abort:()=>state.aborts++,onProgressUpdate:cb=>{state.progress=cb;}};},getFileInfo:o=>{if(!state.holdInfo)o.success({size:state.size});},getFileSystemManager:()=>({readFile:o=>{const part=b.subarray(o.position,o.position+o.length);o.success({data:part.buffer.slice(part.byteOffset,part.byteOffset+part.byteLength)});}})};return {b,state,pack,api};}
test('fixed public download verifies exact size and digest before return',async()=>{const f=fixture(),r=await download(f.api,f.pack);assert.equal(r.path,'http://tmp/test');assert.equal(f.state.url,'https://hiking-earth.nanyu20050927.chatgpt.site/client-app/static/offline-maps/test.pmtiles');assert.ok(f.state.aborts>=1);});
test('invalid manifest never downloads',async()=>{const f=fixture();await assert.rejects(download(f.api,{...f.pack,url:'https://external/map'}));assert.equal(f.state.url,'');});
test('status size and checksum failures never return a file',async()=>{for(const failure of ['status','size','digest']){const f=fixture();if(failure==='status')f.state.status=404;if(failure==='size')f.state.size=128;if(failure==='digest')f.pack.sha256='0'.repeat(64);await assert.rejects(download(f.api,f.pack));}});
test('deadline also terminates hung file information stage',async()=>{const f=fixture();f.state.holdInfo=true;const promise=download(f.api,f.pack);await Promise.resolve();await Promise.resolve();timeout();await assert.rejects(promise,/超时/);assert.ok(f.state.aborts>=1);});
