const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('../../app/node_modules/typescript');
const readerExports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/src/services/basemap-file-reader.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:readerExports});
const exportsObject={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/src/services/wechat-basemap-store.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:exportsObject,require:()=>readerExports});
function fixture(){let rows='',writes=0;const files=new Map(),calls=[];const api={getStorageSync:()=>rows,setStorageSync:(k,v)=>{writes++;if(api.failWrite)throw Error('disk');rows=v;},getSavedFileInfo:o=>files.has(o.filePath)?o.success({size:files.get(o.filePath)}):o.fail(),saveFile:o=>{calls.push('save');const path='wxfile://saved-'+calls.length;files.set(path,api.size);o.success({savedFilePath:path});},removeSavedFile:o=>{calls.push('remove');if(api.failRemove)o.fail();else{files.delete(o.filePath);o.success();}},size:1000};return {api,files,calls,get writes(){return writes;},get rows(){return rows;},store:exportsObject.createWechatMapStore(api,async(path,bytes)=>{calls.push('validate');if(api.failValidation)throw Error('bad');})};}
test('save validates temporary and saved file, list restores persistent index',async()=>{const f=fixture(),r=await f.store.save('wxfile://temp',1000,'Lantau');assert.equal(r.bytes,1000);assert.equal((await f.store.list())[0].path,r.path);assert.deepEqual(f.calls,['validate','save','validate']);assert.equal(f.writes,1);});
test('failed inventory write cleans saved file and preserves old inventory',async()=>{const f=fixture();f.api.failWrite=true;await assert.rejects(f.store.save('wxfile://temp',1000,'Lantau'));assert.equal(f.files.size,0);assert.equal(f.rows,'');});
test('size mismatch rolls back and invalid temporary archive is never saved',async()=>{const f=fixture();f.api.size=2000;await assert.rejects(f.store.save('wxfile://temp',1000,'Lantau'));assert.equal(f.files.size,0);f.api.failValidation=true;f.calls.length=0;await assert.rejects(f.store.save('wxfile://temp',1000,'Lantau'));assert.deepEqual(f.calls,['validate']);});
test('concurrent saves share serial inventory and failed deletion restores index',async()=>{const f=fixture();await Promise.all([f.store.save('wxfile://a',1000,'A'),f.store.save('wxfile://b',1000,'B')]);assert.equal((await f.store.list()).length,2);f.api.failRemove=true;await assert.rejects(f.store.remove(f.rows[0].id));assert.equal((await f.store.list()).length,2);f.api.failRemove=false;await f.store.remove(f.rows[0].id);assert.equal((await f.store.list()).length,1);});
test('corrupted duplicate oversized and external paths reject',()=>{const row={id:'wm-a',name:'a',path:'wxfile://a',bytes:1000,savedAt:1};for(const value of [{},[row,row],[{...row,path:'https://remote'}],[{...row,bytes:64*1024*1024+1}],Array.from({length:4},(_,i)=>({...row,id:'wm-'+i,path:'wxfile://'+i,bytes:64*1024*1024}))])assert.throws(()=>exportsObject.validateWechatMapInventory(value));});
test('existing saved path is never deleted when save callback reuses it',async()=>{const f=fixture(),r=await f.store.save('wxfile://temp',1000,'A');f.api.saveFile=o=>o.success({savedFilePath:r.path});await assert.rejects(f.store.save('wxfile://again',1000,'B'));assert.equal(f.files.get(r.path),1000);assert.equal((await f.store.list()).length,1);assert.ok(!f.calls.includes('remove'));});
