<template><scroll-view scroll-y class="page"><text class="title">官方路线资料审核</text><text>需要管理员账号。官方来源域名由服务端配置；开放状态有效期最多七天，轨迹授权另行审核。</text><input v-model="keyword" placeholder="搜索路线" /><button v-for="r in matching" :key="r.id" @click="choose(r.id)">{{r.name}} · {{r.region}}</button><text>路线 {{routeName||'未选择'}}</text><picker :range="statuses" :value="statuses.indexOf(status)" @change="status=statuses[Number($event.detail.value)]"><button>状态：{{status}}</button></picker><input v-model="sourceUrl" placeholder="官方 HTTPS 资料链接" /><input v-model="checkedAt" placeholder="核验日期，如 2026-10-05T00:00:00+08:00" /><textarea v-model="summary" maxlength="3000" placeholder="资料摘要" /><textarea v-model="riskNotice" maxlength="3000" placeholder="风险与预约提示" /><text>{{message}}</text><button :disabled="busy||!routeId" @click="save">提交审核资料</button></scroll-view></template>
<script setup lang="ts">
import {ref,computed} from 'vue';import {ROUTES} from '@/services/route-catalog';import {callCloud} from '@/services/cloud';import type {RouteStatus} from '@shared/types/route';
const keyword=ref(''),routeId=ref(''),sourceUrl=ref(''),checkedAt=ref(new Date().toISOString()),summary=ref(''),riskNotice=ref(''),status=ref<RouteStatus>('待核验'),version=ref(0),message=ref(''),busy=ref(false);let selection=0;
const statuses:RouteStatus[]=['待核验','开放中','即将开放','临时关闭','永久关闭'];const matching=computed(()=>keyword.value?ROUTES.filter(r=>`${r.name} ${r.region}`.includes(keyword.value)).slice(0,10):[]);const routeName=computed(()=>ROUTES.find(r=>r.id===routeId.value)?.name);
async function choose(id:string){const token=++selection;routeId.value=id;keyword.value='';version.value=0;message.value='';const route=ROUTES.find(r=>r.id===id);summary.value=route?.summary||'';riskNotice.value=route?.archive.riskNotice||'';sourceUrl.value=route?.archive.source.url||'';status.value='待核验';busy.value=true;
 try{for(let page=0;page<100;page++){const result=await callCloud<{items:any[];hasMore:boolean}>('route-manage',{action:'list',page});if(token!==selection)return;if(!result.ok||!result.data)throw new Error(result.errMsg||'读取审核版本失败');const prior=result.data.items.find(r=>r.routeId===id);if(prior){version.value=prior.version;sourceUrl.value=prior.sourceUrl;summary.value=prior.summary;riskNotice.value=prior.riskNotice;status.value=prior.status;return;}if(!result.data.hasMore)return;}throw new Error('审核目录超过读取范围，请稍后再试');}catch(e:any){if(token===selection){routeId.value='';message.value=e.message;}}finally{if(token===selection)busy.value=false;}}
async function save(){busy.value=true;message.value='';try{const result=await callCloud<{version:number}>('route-manage',{action:'save',routeId:routeId.value,sourceUrl:sourceUrl.value,checkedAt:checkedAt.value,status:status.value,summary:summary.value,riskNotice:riskNotice.value,version:version.value});if(!result.ok||!result.data)throw new Error(result.errMsg||'保存失败');version.value=result.data.version;message.value='已保存云端审核资料；其他端刷新后同步。';}catch(e:any){message.value=e.message;}finally{busy.value=false;}}
</script><style scoped>.page{box-sizing:border-box;padding:30rpx;background:#0f141b;color:#eef4ea;min-height:100vh}.title{font-size:36rpx}text{display:block;margin:20rpx 0}input,textarea{padding:20rpx;background:#1a2430;margin:15rpx 0;width:100%;box-sizing:border-box}button{margin:15rpx 0}</style>
